### ISSUE TITLE
subset testing bug

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazmol#80]
This bug may be system specific (Debian one one machine, versus Ubuntu on genapp server).

======================================================================
ERROR: test_1CRN_mask_all (__main__.Test_intg_subset_Mask_get_dihedral_subset_mask)
test a small protein (crambin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/curtisj/git_working_copies/zazmol/src/python/test_sasmol/test_subset/test_intg_subset_Mask_get_dihedral_subset_mask.py", line 331, in test_1CRN_mask_all
    result_farray = self.o.get_dihedral_subset_mask(flexible_residues,mtype)
  File "/home/curtisj/anaconda3/lib/python3.9/site-packages/sasmol/subset.py", line 102, in get_dihedral_subset_mask
    sasmol.mask.get_mask_array(farray, name, resid, flexible_residues, nresidues, mtype)
  File "/home/curtisj/anaconda3/lib/python3.9/site-packages/sasmol/mask.py", line 66, in get_mask_array
    return _mask.get_mask_array(farray, nname, resid, flexible_residues, nresidues, mtype)
TypeError: list must contain strings

**Comment by madscatt** [comment]
https://stackoverflow.com/questions/48391926/python-swig-in-typemap-does-not-work

https://stackoverflow.com/questions/22487780/what-do-i-use-instead-of-pystring-asstring-when-loading-a-python-module-in-3-3

**Comment by madscatt** [comment]
Updated mask.i for python 3.  Tests pass.
