### ISSUE TITLE
python 3 read dcd does not work correctly

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazmol#86]
```
eading 39 frames from ./run_m1.dcd

. Traceback (most recent call last):
  File "/Users/curtisj/git_working_copies/zazzie/src/sassie/tools/merge_utilities/gui_mimic_merge_utilities.py", line 178, in <module>
    run_gui = gui_mimic_merge_utilities(test, paths)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/curtisj/git_working_copies/zazzie/src/sassie/tools/merge_utilities/gui_mimic_merge_utilities.py", line 153, in __init__
    run_module(self)
  File "/Users/curtisj/git_working_copies/zazzie/src/sassie/tools/merge_utilities/gui_mimic_merge_utilities.py", line 137, in run_module
    this_merge_utilities.main(self.variables, txtQueue)
  File "/Users/curtisj/anaconda3/lib/python3.11/site-packages/sassie/tools/merge_utilities/merge_utilities.py", line 97, in main
    self.merge_utilities()
  File "/Users/curtisj/anaconda3/lib/python3.11/site-packages/sassie/tools/merge_utilities/merge_utilities.py", line 495, in merge_utilities
    self.merge_trajectory_files()
  File "/Users/curtisj/anaconda3/lib/python3.11/site-packages/sassie/tools/merge_utilities/merge_utilities.py", line 584, in merge_trajectory_files
    m1.read_dcd_step(dcdfile, j)
  File "/Users/curtisj/anaconda3/lib/python3.11/site-packages/sasmol/dcd_io.py", line 279, in read_dcd_step
    result=dcdio.read_dcdstep(filepointer,tx,ty,tz,num_fixed,frame,reverseEndian,charmm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/curtisj/anaconda3/lib/python3.11/site-packages/sasmol/dcdio.py", line 66, in read_dcdstep
    return _dcdio.read_dcdstep(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wrong number or type of arguments for overloaded function 'read_dcdstep'.
  Possible C/C++ prototypes are:
    read_dcdstep(FILE *,int,float *,float *,float *,int,int,int,int)
    my_read_dcdstep(FILE *,int,float *,int,float *,int,float *,int,int,int,int)
```

**Comment by madscatt** [comment]
Wrote new C-extensions to Python for all dcd_io methods.  Updated all file_io tests.  Passed.  It should be ready for alpha testing.  We do not use SWIG and the numpy.i method any longer.

**Comment by madscatt** [comment]
(base) curtisj@PN130556 test_file_io % pytest *
========================= test session starts =========================
platform darwin -- Python 3.11.5, pytest-7.4.0, pluggy-1.0.0
rootdir: /Users/curtisj/git_working_copies/zazmol
plugins: anyio-3.5.0
collected 164 items

test_intg_file_io_Files_close_dcd_read.py ...ss.sss             [  5%]
test_intg_file_io_Files_close_dcd_write.py ...ss.sss            [ 10%]
test_intg_file_io_Files_init.py .                               [ 11%]
test_intg_file_io_Files_initialize_children.py .............    [ 19%]
test_intg_file_io_Files_open_dcd_read.py ..s.sss                [ 23%]
test_intg_file_io_Files_open_dcd_write.py ...ss.sss             [ 29%]
test_intg_file_io_Files_read_dcd.py ...                         [ 31%]
test_intg_file_io_Files_read_dcd_step.py .....sssss...          [ 39%]
test_intg_file_io_Files_read_pdb.py ................            [ 48%]
test_intg_file_io_Files_read_single_dcd_step.py .....sssss...   [ 56%]
test_intg_file_io_Files_write_dcd.py ..s...                     [ 60%]
test_intg_file_io_Files_write_dcd_frames.py ....s...            [ 65%]
test_intg_file_io_Files_write_dcd_header.py ..s..               [ 68%]
test_intg_file_io_Files_write_dcd_step.py ...s......            [ 74%]
test_intg_file_io_Files_write_pdb.py ...s...                    [ 78%]
test_unit_file_io_Files_check_error.py ..                       [ 79%]
test_unit_file_io_Files_element_filter.py ...........           [ 86%]
test_unit_file_io_Files_get_element.py ..............           [ 95%]
test_unit_file_io_Files_get_resnames.py ......                  [ 98%]
test_unit_file_io_Files_print_error.py ..                       [100%]

=================== 130 passed, 34 skipped in 6.10s ===============
